### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by Rogzy-DB** [PlanB-Network/bitcoin-learning-management-system#105]
We can add a Glossary (lexique in french) page under ressources. 

The page should look like this https://www.figma.com/file/8N8qLeToPHxXmz0y3xLXAZ/University?type=design&node-id=1484-314&mode=dev

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/33b54338-b348-4690-bf25-61038a470c08)

The first MD will be only in french but we must prepare to have the markdown in ENG, ESP, IT DE soon after. 
The back is a geant mark down files who will looke like this: 

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/131364678/0fef9b1c-66fa-443e-a6d0-d2d87050475c)

You can DM Loic to have the files to get started. Later we will have to connect to his githup repo 

https://twitter.com/Loic_Pandul

'''
# <div align="center">C</div>

&nbsp;

**CANAL DE PAIMENT -** Dans le cadre du Lightning Network, un canal de paiement est une connexion bidirectionnelle entre deux nœuds Lightning et qui permet de faire des échanges de bitcoins off-chain. On-chain, un canal de paiement est représenté par une adresse multi-signatures 2/2 détenue par les deux participants. Le canal de paiement nécessite une transaction on-chain pour son ouverture et une transaction off-chain pour sa fermeture. Entre ces deux évènements, les utilisateurs du canal peuvent réaliser un très grand nombre d'échanges de bitcoins off-chain, sur le Lightning Network, sans nécessiter une activité on-chain. Sur Lightning, il est possible de router un paiement à travers plusieurs canaux de paiements et plusieurs nœuds, afin d'envoyer des bitcoins sans forcément ouvrir un canal direct avec le receveur.

&nbsp;

**CHARGE UTILE (PAYLOAD) -** Dans le contexte général de l'informatique, une charge utile désigne les données essentielles transportées dans un paquet de données plus large. Par exemple, dans une adresse SegWit V0 sur Bitcoin, la charge utile correspond au hachage de la clé publique, sans les diverses métadonnées (le HRP, le séparateur, la version de SegWit et la somme de contrôle). Par exemple, sur l'adresse `bc1qc2eukw7reasfcmrafevp5dhv8635yuqays50gj`, nous avons : 
- `bc` : la partie lisible par l'homme (HRP) ;
- `1` : le séparateur ;
- `q` : la version de SegWit. Ici, c'est la version 0 ;
- `c2eukw7reasfcmrafevp5dhv8635yuqa` : la charge utile, ici, le hachage de la clé publique ;
- `ys50gj` : la somme de contrôle.

&nbsp;

**CHIFFRER (CHIFFREMENT) -** Méthode cryptographique permettant de convertir une information brute en information chiffrée. Une information chiffrée masque la signification originale des données pour empêcher qu'elles ne soient connues. Le chiffrement consiste en une série de transformations effectuées sur l'information originale à l'aide d'une clé. Si ces transformations sont réversibles, le processus d'inversion correspondant est appelé « déchiffrement », et il permet de restaurer les informations à leur état brut.

**Comment by trigger67** [comment]
@Rogzy-DB some info we need to finalize this : 
- A logo for the glossary, to put in the /resources page
- A subtitle for the menu, ie the text to put under "Glossary"
