### ISSUE TITLE
creation of the exam booking page

### ISSUE THREAD

**Issue by Rogzy-DB** [PlanB-Network/bitcoin-learning-management-system#197]
We want to allow our studient to book an exam spot for the physical exam taken place at adopting and bitcoin africa confenrence

- Show of the potentiel dat
- popup with mor einfo and book option
- paiement to book and mail confirmation and we gather the dat a

- some texte and explaincation of th eprocess
- some company that truste us 
- get a link to study more

obviously create the exam but that's asio'job

![Image](https://user-images.githubusercontent.com/131364678/246537614-5fc35474-1435-4343-a0c2-5f45ff33bcf7.png)

**Comment by mumacadam** [comment]
issue to close cause it's been done already (exam events )
