### ISSUE TITLE
Register popup : add email option in register box

### ISSUE THREAD

**Issue by mumacadam** [PlanB-Network/bitcoin-learning-management-system#338]
redesign and integration of the email field inside the register pop up.

![Image](https://github.com/DecouvreBitcoin/sovereign-university/assets/144212410/5bb7fa50-5be9-4739-8655-821b024b5a08)

**Comment by mumacadam** [comment]
I made a few changes on the text (sentence, colour and padding, and position related to the text field). 

you can find the mock up here : https://www.figma.com/design/1fto3tLdJH7hOcbQ7vT9dg/PlanB-Network---Work-in-progress?node-id=9275-138900&m=dev

**Comment by mumacadam** [comment]
![Image](https://github.com/user-attachments/assets/eeb85095-fa6b-42d0-8d08-4b9549016404)
 typo : "in" is missing"

**Comment by trigger-xyz** [comment]
Typo fixed

**Comment by Rogzy-DB** [comment]
Missing the wierd B at the bottom: 

"No need for an account to start learning at Plan B Network !"

PLease let me know who i should tag for future typo error.

**Comment by trigger-xyz** [comment]
No need to tag anyone. Also it can be fixed directly in weblate.
