### ISSUE TITLE
Tutorials view page : new mobile version

### ISSUE THREAD

**Issue by Rogzy-DB** [PlanB-Network/bitcoin-learning-management-system#52]
a mobile version has been created for this page, to improve user experience : 

https://www.figma.com/file/8N8qLeToPHxXmz0y3xLXAZ/University?type=design&node-id=38-2383&mode=dev

![Image](https://user-images.githubusercontent.com/144212410/266866060-7011d5af-9e81-468c-ac62-1893a252b21c.png)

**Comment by trigger67** [comment]
@mumacadam Hey, is it possible to have the same design for the courses and the tutorials content ?
On mobile and desktop ?

And also to have not only paragraph titles, but also sub-titles ?

Thanks :)
