### ISSUE TITLE
create FilterBar component 

### ISSUE THREAD

**Issue by ac1dbunny21** [PlanB-Network/bitcoin-learning-management-system#6]
we want to: 
1. create a new FilterBar component, that should be "collapsable"
   - in `collapsed` state, the component should look like [that](https://www.figma.com/file/foyvlfIOyL88zXCZXSQbzK/DecouvreBitcoin?type=design&node-id=754-36996&t=N8M6EoSkg3qxjWjq-4)
   - in `expanded` state, the component should look like [that](https://www.figma.com/file/foyvlfIOyL88zXCZXSQbzK/DecouvreBitcoin?type=design&node-id=754-36767&t=N8M6EoSkg3qxjWjq-4)
       - it should contain selector for `difficulty` (single/radio) and `tags` (multi/checkboxes)
   - the component should accept the following props (non exhaustive):
       - onFilterChange: a function used in container to refetch items with updated filters
2. adapt our Storybook accordingly 

![Image](https://github.com/blc-org/sovereign-academy/assets/38882571/7453d491-b1b9-4ca2-b2c5-4a693e489b24)
![Image](https://github.com/blc-org/sovereign-academy/assets/38882571/04f64a2a-fafd-4452-8f4e-caf94c147b22)

**Comment by louneskmt** [comment]
There is the `collapsed` version (or at least some of it) in the `Builders` page.

**Comment by louneskmt** [comment]
Component created in 71fd63a6f6775fa070ceb25cff00a3e28e69778a and 2a774879308aba1514c239cdc50ec3093e2bcec3. We only have the `collapsed` state but we don't need much more for now.
