### ISSUE TITLE
create SideNavigation component 

### ISSUE THREAD

**Issue by ac1dbunny21** [PlanB-Network/bitcoin-learning-management-system#7]
we want to:
1. create a new component to [enable side navigation in a ressource page](https://www.figma.com/file/foyvlfIOyL88zXCZXSQbzK/DecouvreBitcoin?type=design&node-id=725-20689&t=H2Cig8i5iqMRCZ2A-4)
   - the SideNavigation componet should accept the following props
        - sections: `Array<TBD>`
        - footer: `JSX.Element[]` a list of items to render right below the nav
2. adapt our storybook accordingly

**Comment by louneskmt** [comment]
Two variants:

![Image](https://github.com/blc-org/sovereign-academy/assets/38882571/fb10f8f0-b7be-4e85-a907-9ae687bedd43)
![Image](https://github.com/blc-org/sovereign-academy/assets/38882571/4deba49a-50bf-4232-8909-6ec255744583)
